In [ ]:
import numpy as np

In [ ]:
def z_score_normalization(data):
    """
    Normalise les caractéristiques d'un ensemble de données en utilisant la méthode Z-score.

    Args:
    - data : un tableau NumPy contenant les données à normaliser. Chaque colonne représente une caractéristique.

    Returns:
    - data_normalized : le tableau NumPy contenant les données normalisées.
    - mean : le tableau NumPy contenant les moyennes de chaque caractéristique avant normalisation.
    - std : le tableau NumPy contenant les déviations standard de chaque caractéristique avant normalisation.
    """
    # Calcul des moyennes et des déviations standard de chaque caractéristique
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    mean_no_axis = np.mean(data)
    std_dev_no_axis = np.std(data)
    # Normalisation des données en utilisant la méthode Z-score
    data_normalized = (data - mean) / std

    return data_normalized, mean, std, mean_no_axis,  std_dev_no_axis

# Exemple d'utilisation :
data = np.array([[1, 12, 33],
                 [4, 5, 26],
                 [7, 3, 9]])

data_normalized, mean, std,mean_no_axis, std_dev_no_axis = z_score_normalization(data)
print("-Données normalisées :\n", data_normalized)
print("\n-Moyennes avant normalisation :\n", mean)
print("\n-Déviations standard avant normalisation :", std)
print("\n-Moyenne sur l'ensemble du tableau aplati (pas d'axe spécifié):", mean_no_axis)
print("\n-Écart-type sur l'ensemble du tableau aplati (pas d'axe spécifié):", std_dev_no_axis)


-Données normalisées :
 [[-1.22474487  1.38218948  1.02538886]
 [ 0.         -0.43193421  0.3307706 ]
 [ 1.22474487 -0.95025527 -1.35615946]]

-Moyennes avant normalisation :
 [ 4.          6.66666667 22.66666667]

-Déviations standard avant normalisation : [ 2.44948974  3.8586123  10.07747764]

-Moyenne sur l'ensemble du tableau aplati (pas d'axe spécifié): 11.11111111111111

-Écart-type sur l'ensemble du tableau aplati (pas d'axe spécifié): 10.429066693562058
